Numpy Basic Operations

In [1]:
#import numpy 

import numpy as np

In [4]:
#creating one dimensional numpy array

a=np.array([1,2,3])
print (a)

[1 2 3]


In [5]:
#get shape of numpy array

a.shape

(3,)

In [6]:
#get numpy array dimension
a.ndim

1

In [7]:
#get numpy array data type
a.dtype

dtype('int32')

In [10]:
#get size
(a.itemsize) 

4

In [11]:
#get total size
a.nbytes

12

# Accessing/ Changing specific elements rows, columns

In [13]:
b=np.array([[1,2,3],[4,5,6]])
b.ndim

2

In [14]:
b


array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
#access specifi element in this case 2 [row, column]

b[0, 1:2]

array([2])

In [17]:
#get first row
a[0:]

array([1, 2, 3])

In [38]:
#get first column 
print(b[0:2, 0:1])
print(b[:, 2:])

[[1]
 [4]]
[[3]
 [6]]


In [53]:
#more fancy indexing start index, end index, step 
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
a[0, 0:6:2]

array([1, 3, 5])

In [56]:
#change value at specific index
a[0:1]=20
a[0:5]=20
a

array([[20,  2,  3,  4,  5, 20,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

# 3d array

In [69]:
c=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [58]:
c.ndim

3

In [70]:
c[0, 1, 1]

4

# Initializaing different types of matrix

In [73]:
d= np.zeros(5)
d

array([0., 0., 0., 0., 0.])

In [74]:
#matrix of zeros
e=np.zeros((2,3)) #(rows, columns)
e

array([[0., 0., 0.],
       [0., 0., 0.]])

In [77]:
#matrix of ones
f= np.ones((4,3,4))
f

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [78]:
#any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [79]:
#full like
np.full_like(f,4)

array([[[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]],

       [[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]],

       [[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]],

       [[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]]])

In [84]:
#Random decimal numbers
np.random.rand(4,2,3)

array([[[0.39538037, 0.31570222, 0.6053435 ],
        [0.43066591, 0.68100926, 0.48410727]],

       [[0.89192279, 0.00550921, 0.82694627],
        [0.98999353, 0.34745183, 0.67046187]],

       [[0.07694515, 0.96558965, 0.73050623],
        [0.17369425, 0.27421086, 0.78271899]],

       [[0.23498017, 0.92528288, 0.34180859],
        [0.02610688, 0.08365252, 0.20028767]]])

In [82]:
#random integer value (it will generate random values between 0 and 6)
np.random.randint(7, size=(3,3))

array([[4, 4, 2],
       [0, 2, 2],
       [4, 4, 1]])

In [85]:
#identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [90]:
#repeat an array 
arr=np.array([[1,2,3]])
r=np.repeat(arr,3, axis=1)
print(r)
r=np.repeat(arr,3, axis=0)
print(r)

[[1 1 1 2 2 2 3 3 3]]
[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [93]:
output= np.ones((5,5))
output_2= np.zeros((3,3))
output_2[1,1]=9
output[1:4,1:4]=output_2
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


# Mathematics

In [96]:
a=np.array([[1,2,3],[7,8,9]])
b= np.array([4,5,6])
c=a+b
c

array([[ 5,  7,  9],
       [11, 13, 15]])

In [97]:
a=np.array([[1,2,3],[7,8,9]])
b= np.array([4,5,6])
c=a-b
c

array([[-3, -3, -3],
       [ 3,  3,  3]])

In [98]:
a=np.array([[1,2,3],[7,8,9]])
b= np.array([4,5,6])
c=a*b
c

array([[ 4, 10, 18],
       [28, 40, 54]])

In [99]:
a=np.array([[1,2,3],[7,8,9]])
b= np.array([4,5,6])
c=a/b
c

array([[0.25, 0.4 , 0.5 ],
       [1.75, 1.6 , 1.5 ]])

In [100]:
a=np.array([[1,2,3],[7,8,9]])
a**2

array([[ 1,  4,  9],
       [49, 64, 81]], dtype=int32)

In [101]:
np.sin(a)

array([[0.84147098, 0.90929743, 0.14112001],
       [0.6569866 , 0.98935825, 0.41211849]])

In [102]:
np.cos(a)

array([[ 0.54030231, -0.41614684, -0.9899925 ],
       [ 0.75390225, -0.14550003, -0.91113026]])

In [103]:
np.tan(a)

array([[ 1.55740772, -2.18503986, -0.14254654],
       [ 0.87144798, -6.79971146, -0.45231566]])

# Linear Algebra

In [106]:
#if two matrix are of different number of columns and rows 
a=np.ones((2,3))
b=np.full((3,2),2)
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

# Statistics

In [110]:
#find minimum value
stats=np.array([[1,2,3],[4,5,6]])
print(np.min(stats, axis=1)) # row wise minimum value 
print(np.min(stats, axis=0)) # column wise minimu value 
print(np.min(stats)) # overall minimum value

[1 4]
[1 2 3]
1


In [ ]:
#find maximum value
stats=np.array([[1,2,3],[4,5,6]])
print(np.max(stats, axis=1)) # row wise maximun value 
print(np.max(stats, axis=0)) # column wise maximum value 
print(np.max(stats)) # overall maximum value

In [112]:
#sum of all values
np.sum(stats)

21

# Reorganizing Array

In [119]:
array_1= np.array([[1,2,3,4],[4,5,6,8]])
print(array_1)

array_2=array_1.reshape((2,2,2))
print(array_2)

[[1 2 3 4]
 [4 5 6 8]]
[[[1 2]
  [3 4]]

 [[4 5]
  [6 8]]]


In [121]:
#vertical stacking
a= np.array([1,2,3])
b= np.array([4,5,6])
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [122]:
#horizontal stacking
a= np.array([1,2,3])
b= np.array([4,5,6])
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

# load data from file 

In [ ]:
file= np.genfromtxt('data.txt', delimiter=',')
file.astype('int32')
file

# Boolean masking and advance indexing 

In [ ]:
#it will print all values greater than 50 
file[file>=50 ]

In [ ]:
np.any(file>50, axis=0)

In [ ]:
((file>50) & (file<100))